name: moengage_flutter_android
description: Android implementation of the moengage_flutter plugin
version: 3.3.1
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: moengage_flutter
    platforms:
      android:
        package: com.moengage.flutter
        pluginClass: MoEngageFlutterPlugin
        dartPluginClass: MoEngageFlutterAndroid

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter_platform_interface: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  
