name: moengage_geofence
description:  Flutter Plugin for using Geofence feature of MoEngage Platform.
version: 1.6.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MoEngageGeofencePlugin
      android:
        package: com.moengage.flutter.geofence
        pluginClass: MoEngageGeofencePlugin
