name: moengage_inbox_ios
description: iOS implementation of the moengage_inbox plugin
version: 3.3.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: moengage_inbox
    platforms:
      ios:
        pluginClass: MoEngageInboxPlugin
        dartPluginClass: MoEngageInboxIOS

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^9.0.0
  moengage_inbox_platform_interface: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  
