name: moengage_flutter_platform_interface
description: A common platform interface for the moengage_flutter plugin.
version: 3.0.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  collection: ^1.16.0
  flutter_test:
    sdk: flutter
