name: moengage_flutter
description: Flutter Plugin for MoEngage Platform. MoEngage is an Intelligent Customer Engagement Platform
version: 6.1.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  assets:
    - config.json
  plugin:
    platforms:
      android:
        default_package: moengage_flutter_android
      ios:
        default_package: moengage_flutter_ios
      web:
        default_package: moengage_flutter_web

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter_android: ^1.1.0
  moengage_flutter_ios: ^1.1.0
  moengage_flutter_platform_interface: ^1.1.0
  moengage_flutter_web: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
