name: moengage_geofence_ios
description: iOS implementation of the moengage_geofence plugin
version: 4.2.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: moengage_geofence
    platforms:
      ios:
        pluginClass: MoEngageGeofencePlugin
        dartPluginClass: MoEngageGeofenceIOS

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^10.0.0
  moengage_geofence_platform_interface: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  