name: moengage_geofence_platform_interface
description: A common platform interface for the moengage_geofence plugin.
version: 2.0.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^7.0.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
