name: moengage_geofence
description:  Flutter Plugin for using Geofence feature of MoEngage Platform.
version: 3.1.1
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^7.1.1
  moengage_geofence_android: 2.1.1
  moengage_geofence_ios: 2.2.0
  moengage_geofence_platform_interface: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: moengage_geofence_android
      ios:
        default_package: moengage_geofence_ios