name: moengage_flutter_web
description: Web implementation of the moengage_flutter plugin
version: 2.0.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: moengage_flutter
    platforms:
      web:
        pluginClass: MoEngageFlutterWeb
        fileName: moengage_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  moengage_flutter_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
