name: moengage_geofence_android
description: Android implementation of the moengage_geofence plugin
version: 4.1.2
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: moengage_geofence
    platforms:
      android:
        package: com.moengage.flutter.geofence
        pluginClass: MoEngageGeofencePlugin
        dartPluginClass: MoEngageGeofenceAndroid

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^10.0.0
  moengage_geofence_platform_interface: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0