name: moengage_cards
description: MoEngage Cards Plugin
version: 2.0.0
homepage: https://moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: moengage_cards_android
      ios:
        default_package: moengage_cards_ios

dependencies:
  flutter:
    sdk: flutter
  moengage_cards_android: ^1.0.0
  moengage_cards_ios: ^1.0.0
  moengage_cards_platform_interface: ^1.0.0
  moengage_flutter: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  
