name: moengage_inbox
description: Flutter Plugin for using Notification Center feature of MoEngage Platform, to provide an Inbox to view all the notifications received by your application.
version: 6.1.1
homepage: https://moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^7.1.1
  moengage_inbox_android: ^2.1.1
  moengage_inbox_ios: ^2.2.0
  moengage_inbox_platform_interface: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

flutter:
  assets:
    - config.json
  plugin:
    platforms:
      android:
        default_package: moengage_inbox_android
      ios:
        default_package: moengage_inbox_ios